### ISSUE TITLE
Configuration Options to Protect Players by Difficulty

### ISSUE THREAD

**Issue by Hextator** [Mrcactus1215/mob-justice#3]
There is currently no way for the plugin to provide immunity to players for being Mediumcore or Hardcore.

The plugin should be updated with config options for making players immune to the plugin's effects based on their difficulty, for all of the (currently 4 (should Journey be counted?)) difficulty settings a player may have.

- It may be desirable for Classic characters to be made immune independently of other difficulty immunities.
- Hardcore may not make sense as being vulnerable when Mediumcore is not, but the options to set immunity for each should operate independently for maximum flexibility.
- Journey may be negligible, but if an option can support making Journey players immune, it should be added.

**Comment by MsCactus1215** [comment]
https://github.com/Pryaxis/TShock/blob/b862baa220cef61a7818f1f9d25ee676b337052c/TShockAPI/GetDataHandlers.cs

@line 2308

The Data Handler can check what difficulty the player is on, and use in the code accordingly

**Comment by MsCactus1215** [comment]
Implemented in update 2.2.20210413.1
