### ISSUE TITLE
Command Syntax Rework

### ISSUE THREAD

**Issue by Hextator** [Mrcactus1215/mob-justice#5]
As per El Cactolo's discussions on Discord:

- The command syntax for this plugin's commands would be more clear if all of the commands were subcommands of a parent command:
`/lynch`
- Entering the parent command with no arguments could report usage information and plugin meta data, which should be implemented in some form anyway, as that information that is currently not available to players via commands.
  ```
  Mob Justice plugin by Hextator and Valdas.
  Version: {VERSION_NUMBER}
  We're gonna get you, Mouserat!
  Available subcommands: vote, myvotes, showvotes, force, showforced
  Syntax: /lynch <subcommand> [subcommandArguments ...]
  ```
  - In the previous example, the available subcommands list should be trimmed to only show commands available to that specific player.
- Subcommands with arguments should report their usage syntax when no arguments are provided:
  `/lynch vote`
  would output
  ```
  Votes to lynch a player specified by the "targetName" argument.
  Syntax: /lynch vote <targetName>
  ```
- Subcommands with no arguments should perform their intended function, followed by any relevant description for what arguments may be provided if the command may have them supplied:
  `/lynch myvotes`
  would output
  ```
  You are currently voting to lynch: Valdas, Hextator
  A name may be supplied as the "targetName" argument to check if you are voting to lynch a specific player.
  Syntax: /lynch myvotes <targetName>
  ```

**Comment by MsCactus1215** [comment]
Added in Mob-Justice Ver. 2.2.20220207.1
